import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/client-components/navbar/navbar.component";
import Link from "next/link";
import AuthorizationService from "@/services/authorization-service/authorization-service";
import UserBox from "@/client-components/user-box/userbox.component";
import QueryWrapper from "@/client-components/query-wrapper/query-wrapper";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh`}
        >
          <QueryWrapper>
            <Navbar>
              <h1 className="text-2xl font-bold">Noted!</h1>
              <Link href={"/questions"} >Otázky</Link>
              <UserBox />
            </Navbar>
            <div className="flex flex-col items-center justify-start pt-20 w-full h-full p-4 bg-gray-100">
              {children}
              <Toaster position="top-center" />
            </div>
          </QueryWrapper>
      </body>
    </html>
  );
}
